### ISSUE TITLE
Control with StreamDeck+ Dial?

### ISSUE THREAD

**Issue by ckelsoe** [VictorGrycuk/streamdeck-magnifier#3]
This is a feature request, not an issue. It would be awesome to control the zoom using a dial on the StreamDeck+.

**Comment by VictorGrycuk** [comment]
Hi @ckelsoe, that actually sounds awesome. Sadly, I don't have access to a StreamDeck+.
I will close the issue, however, I will reopen it if I find a StreamDeck+ in the future.
